// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using MojTermin.Api.Infrastructure.Data;

#nullable disable

namespace MojTermin.Api.Infrastructure.Data.Migrations
{
    [DbContext(typeof(MojTerminDbContext))]
    [Migration("20260515150000_AddAppointmentContactFullName")]
    partial class AddAppointmentContactFullName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
